apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-gateway.fullname" . }}
  labels:
    {{- include "k8s-gateway.labels" . | nindent 4 }}
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
spec:
  selector:
    {{- include "k8s-gateway.selectorLabels" . | nindent 6 }}
  ports:
  - {port: 53, protocol: UDP, name: udp-53}
  type: LoadBalancer